services:
  data_db:
    image: postgres:14.7
    container_name: "db_hermes"
    restart: always
    command: -p 8801
    ports:
      - "8801:8801"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  data_web:
    image: ghcr.io/skelmis/hermes:master
    container_name: "web_hermes"
    restart: always
    ports:
      - "8800:8800"
    depends_on:
      - data_db
    volumes:
      - projects:/code/.projects
    cpus: 4
    mem_limit: 2g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "hermes.skelmis.co.nz"
      POSTGRES_HOST: db_hermes
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
      POSTGRES_PORT: 8801

volumes:
  projects:

#networks:
#  default:
#    name: spook
#    external: true