# You need to set the relevant passwords
x-shared-variables: &common-variables
  POSTGRES_HOST: db_hermes
  POSTGRES_DB: hermes_db
  POSTGRES_USER: hermes_db_user
  POSTGRES_PASSWORD:
  POSTGRES_PORT: 8801
  REDIS_URL: "redis://default:<PASSWORD>@redis_hermes:8802/0"

services:
  hermes_db:
    image: postgres:16.4
    container_name: "db_hermes"
    restart: always
    command: -p 8801
    ports:
      - "127.0.0.1:8801:8801"
    environment:
      <<: *common-variables
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .db:/var/lib/postgresql/data
  hermes_web:
    image: ghcr.io/skelmis/hermes:master
    container_name: "web_hermes"
    restart: always
    volumes:
      - projects:/code/.projects
    ports:
      - "127.0.0.1:8800:8800"
    depends_on:
      - hermes_db
      - hermes_redis
    environment:
      <<: *common-variables
      SERVING_DOMAIN: "hermes.skelmis.co.nz"
      CSRF_TOKEN:
  hermes_saq:
    image: ghcr.io/skelmis/hermes_saq:master
    container_name: "saq_hermes"
    restart: always
    # Uncomment if you want the SAQ dashboard
#    ports:
#      - "127.0.0.1:8803:8080"
    volumes:
      - projects:/code/.projects
    depends_on:
      - hermes_redis
    environment:
      <<: *common-variables
  hermes_redis:
    image: redis:7.4-alpine
    container_name: "redis_hermes"
    restart: always
    ports:
      - '127.0.0.1:8802:8802'
    command: redis-server --port 8802 --save 20 1 --loglevel warning --requirepass <YOURPASSWORDCHOICCE>
    volumes:
      - cache:/data

volumes:
  projects:
  cache:
    driver: local

#networks:
#  default:
#    name: spook
#    external: true