services:
  hermes_db:
    image: postgres:14.7
    container_name: "db_hermes"
    restart: always
    command: -p 8801
    ports:
      - "8801:8801"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  hermes_web:
    image: ghcr.io/skelmis/hermes:master
    container_name: "web_hermes"
    restart: always
    ports:
      - "8800:8800"
    depends_on:
      - hermes_db
    volumes:
      - projects:/code/.projects
    cpus: 4
    mem_limit: 2g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "hermes.skelmis.co.nz"
      POSTGRES_HOST: db_hermes
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
      POSTGRES_PORT: 8801
  hermes_redis:
    image: redis:7.4-alpine
    container_name: "redis_hermes"
    restart: always
    cpus: 1
    mem_limit: 256m
    mem_reservation: 128m
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass haziness-sloppy-cycle-deduct-superman-undertook
    volumes:
      - cache:/data

volumes:
  projects:
  cache:
    driver: local

#networks:
#  default:
#    name: spook
#    external: true