x-shared-variables: &common-variables
  POSTGRES_HOST: db_hermes
  POSTGRES_DB: hermes_db
  POSTGRES_USER: hermes_db_user
  POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
  POSTGRES_PORT: 8801
  REDIS_URL: "redis://default:haziness-sloppy-cycle-deduct-superman-undertook@redis_hermes:8802/0"

services:
  hermes_db:
    image: postgres:14.7
    container_name: "db_hermes"
    restart: always
    command: -p 8801
    ports:
      - "8801:8801"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  hermes_web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: "web_hermes"
    restart: always
    volumes:
      - projects:/code/.projects
    ports:
      - "8800:8800"
    depends_on:
      - hermes_db
      - hermes_redis
    environment:
      <<: *common-variables
      DEBUG: 1
      CSRF_TOKEN: 02bea54b1b317930f14317938f48d785d0adf5909bf19480fcee2fac1253e522
  hermes_saq:
    build:
      context: .
      dockerfile: ./docker/saq/Dockerfile
    container_name: "saq_hermes"
    restart: always
    ports:
      - "8803:8080"
    volumes:
      - projects:/code/.projects
    depends_on:
      - hermes_redis
    environment:
      <<: *common-variables
  hermes_redis:
    image: redis:7.4-alpine
    container_name: "redis_hermes"
    restart: always
    ports:
      - '8802:8802'
    command: redis-server --port 8802 --save 20 1 --loglevel warning --requirepass haziness-sloppy-cycle-deduct-superman-undertook
    volumes:
      - cache:/data

volumes:
  projects:
  cache:
    driver: local

#networks:
#  default:
#    name: spook
#    external: true