[tool.poetry]
name = "hermes"
package-mode = false
description = "A single pane of glass for static code analysis"
authors = ["Skelmis <skelmis.craft@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
piccolo = {extras = ["all"], version = "^1.13.1"}
litestar = "^2.9.1"
uvicorn = "^0.30.3"
piccolo-admin = "^1.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
